name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# evita carreras si hay pushes seguidos
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest -q

      # Opcional: generar demo report y guardarlo como artefacto
      - name: Generate demo HTML report
        run: |
          mkdir -p out
          python -m sshlog.cli --log samples/auth.sample.log --html out/report.html

      - name: Upload demo report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: demo-report-${{ matrix.python-version }}
          path: out/report.html
